export const NHAN_SU_STATUS_OPTIONS = [
    { label: "Đang làm việc", value: "dang_lam_viec", color: "processing" },
    { label: "Nghỉ việc", value: "nghi_viec", color: "default" },
];

export const CHUC_VU_OPTIONS = [
    { label: "Chủ tịch Hội Đồng Thành Viên", value: "chu_tich_hdtv" },
    { label: "Thành viên chuyên trách HĐTV", value: "thanh_vien_hdtv" },
    { label: "Thành viên HĐTV - Tổng Giám Đốc", value: "thanh_vien_hdtv_tgd" },
    { label: "Phó Tổng Giám Đốc", value: "pho_tgd" },
    { label: "Phó Tổng giám đốc - Giám đốc Ban", value: "pho_tgd_gd_ban" },
    { label: "Kế toán trưởng", value: "ke_toan_truong" },
    { label: "Lái xe", value: "lai_xe" },
    { label: "Chuyên viên", value: "chuyen_vien" },
    { label: "Chuyên viên, Văn thư", value: "chuyen_vien_van_thu" },
    { label: "Chánh Văn phòng", value: "chanh_van_phong" },
];

export const PHONG_BAN_NHAN_SU_OPTIONS = [
    { label: "Hội Đồng thành viên", value: "hoi_dong_thanh_vien" },
    { label: "Ban Tổng Giám đốc", value: "ban_tong_giam_doc" },
    { label: "Văn phòng", value: "van_phong" },
];

export const DON_VI_NHAN_SU_OPTIONS = [
    { label: "VEC", value: "VEC" },
    { label: "VEC O&M", value: "VEC_OM" },
];

export const GIOI_TINH_OPTIONS = [
    { label: "Nam", value: "nam" },
    { label: "Nữ", value: "nu" },
];

export const TINH_TRANG_OPTIONS = [
    { label: "Đang làm việc", value: "dang_lam_viec" },
    { label: "Nghỉ việc", value: "nghi_viec" },
];

// Mock data 172 nhân viên
export const mockNhanSuData = [
    {
        id: 1,
        maNV: "VEC0001",
        hoTen: "Trương Việt Đông",
        gioiTinh: "Nam",
        chucVu: "Chủ tịch Hội Đồng Thành Viên",
        phongBan: "Hội Đồng thành viên",
        donVi: "VEC",
        ngaySinh: "17/08/1979",
        dienThoai: "-",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 2,
        maNV: "VEC0002",
        hoTen: "Trần Công Hòa",
        gioiTinh: "Nam",
        chucVu: "Thành viên chuyên trách HĐTV",
        phongBan: "Hội Đồng thành viên",
        donVi: "VEC",
        ngaySinh: "15/05/1975",
        dienThoai: "0913.751.111",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 3,
        maNV: "VEC0003",
        hoTen: "Phạm Hồng Quang",
        gioiTinh: "Nam",
        chucVu: "Thành viên HĐTV - Tổng Giám Đốc",
        phongBan: "Hội Đồng thành viên",
        donVi: "VEC",
        ngaySinh: "06/07/1973",
        dienThoai: "-",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 4,
        maNV: "VEC0004",
        hoTen: "Lê Quang Vũ",
        gioiTinh: "Nam",
        chucVu: "Thành viên chuyên trách HĐTV",
        phongBan: "Hội Đồng thành viên",
        donVi: "VEC",
        ngaySinh: "21/12/1984",
        dienThoai: "0986.832.008",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 5,
        maNV: "VEC0005",
        hoTen: "Nguyễn Thế Cường",
        gioiTinh: "Nam",
        chucVu: "Phó Tổng Giám Đốc",
        phongBan: "Ban Tổng Giám đốc",
        donVi: "VEC",
        ngaySinh: "11/07/1977",
        dienThoai: "-",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 6,
        maNV: "VEC0006",
        hoTen: "Kiều Hưng",
        gioiTinh: "Nam",
        chucVu: "Phó Tổng Giám Đốc",
        phongBan: "Ban Tổng Giám đốc",
        donVi: "VEC",
        ngaySinh: "16/11/1972",
        dienThoai: "-",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 7,
        maNV: "VEC0007",
        hoTen: "Đặng Hoài Nam",
        gioiTinh: "Nam",
        chucVu: "Phó Tổng giám đốc - Giám đốc Ban",
        phongBan: "Ban Tổng Giám đốc",
        donVi: "VEC",
        ngaySinh: "05/09/1971",
        dienThoai: "0915.343.599",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 8,
        maNV: "VEC0008",
        hoTen: "Hàn Mai Nga",
        gioiTinh: "Nữ",
        chucVu: "Kế toán trưởng",
        phongBan: "Ban Tổng Giám đốc",
        donVi: "VEC",
        ngaySinh: "12/12/1981",
        dienThoai: "-",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 9,
        maNV: "VEC0009",
        hoTen: "Lương Ngọc Chính",
        gioiTinh: "Nam",
        chucVu: "Lái xe",
        phongBan: "Văn phòng",
        donVi: "VEC",
        ngaySinh: "28/10/1981",
        dienThoai: "0984.589.274",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 10,
        maNV: "VEC0010",
        hoTen: "Võ Thúc Định",
        gioiTinh: "Nam",
        chucVu: "Chuyên viên",
        phongBan: "Văn phòng",
        donVi: "VEC",
        ngaySinh: "09/07/1980",
        dienThoai: "0989.890.666",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 11,
        maNV: "VEC0011",
        hoTen: "Đào Thị Hạnh",
        gioiTinh: "Nữ",
        chucVu: "Chuyên viên, Văn thư",
        phongBan: "Văn phòng",
        donVi: "VEC",
        ngaySinh: "21/10/1984",
        dienThoai: "0914.880.209",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 12,
        maNV: "VEC0012",
        hoTen: "Lương Bá Hùng",
        gioiTinh: "Nam",
        chucVu: "Lái xe",
        phongBan: "Văn phòng",
        donVi: "VEC",
        ngaySinh: "15/07/1971",
        dienThoai: "0903.292.872",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 13,
        maNV: "VEC0013",
        hoTen: "Nguyễn Công Hưng",
        gioiTinh: "Nam",
        chucVu: "Chánh Văn phòng",
        phongBan: "Văn phòng",
        donVi: "VEC",
        ngaySinh: "11/08/1981",
        dienThoai: "0904.859.596",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 14,
        maNV: "VEC0014",
        hoTen: "Nguyễn Minh Khôi",
        gioiTinh: "Nam",
        chucVu: "Lái xe",
        phongBan: "Văn phòng",
        donVi: "VEC",
        ngaySinh: "20/01/1970",
        dienThoai: "0989.492.866",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 15,
        maNV: "VEC0015",
        hoTen: "Vũ Văn Kiên",
        gioiTinh: "Nam",
        chucVu: "Chuyên viên",
        phongBan: "Văn phòng",
        donVi: "VEC",
        ngaySinh: "03/07/1997",
        dienThoai: "-",
        tinhTrang: "Đang làm việc",
    },
    {
        id: 16,
        maNV: "VEC0016",
        hoTen: "Đào Thị Phương Lan",
        gioiTinh: "Nữ",
        chucVu: "Chuyên viên",
        phongBan: "Văn phòng",
        donVi: "VEC",
        ngaySinh: "17/11/1982",
        dienThoai: "0915.958.882",
        tinhTrang: "Đang làm việc",
    },
    // Thêm dữ liệu để đủ 172 nhân viên
    ...Array.from({ length: 156 }, (_, i) => ({
        id: i + 17,
        maNV: `VEC${String(i + 17).padStart(4, "0")}`,
        hoTen: `Nhân viên ${i + 17}`,
        gioiTinh: i % 3 === 0 ? "Nữ" : "Nam",
        chucVu: ["Chuyên viên", "Nhân viên", "Trưởng phòng", "Phó phòng"][i % 4],
        phongBan: ["Văn phòng", "Tài chính", "Nhân sự", "Kỹ thuật", "Marketing"][i % 5],
        donVi: "VEC",
        ngaySinh: `${String((i % 28) + 1).padStart(2, "0")}/${String((i % 12) + 1).padStart(2, "0")}/${1970 + (i % 30)}`,
        dienThoai: i % 2 === 0 ? `09${String(i).padStart(8, "0")}` : "-",
        tinhTrang: "Đang làm việc",
    })),
];
