CREATE TABLE IF NOT EXISTS VEC_InternalSurvey (
	surveyId BIGINT NOT NULL AUTO_INCREMENT,
	companyId BIGINT DEFAULT 0,
	groupId BIGINT DEFAULT 0,
	userId BIGINT DEFAULT 0,
	userName VARCHAR(255) DEFAULT NULL,
	title VARCHAR(500) NOT NULL,
	description TEXT DEFAULT NULL,
	multipleChoice TINYINT(1) NOT NULL DEFAULT 0,
	status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	startDate DATETIME(6) DEFAULT NULL,
	endDate DATETIME(6) DEFAULT NULL,
	createDate DATETIME(6) DEFAULT NULL,
	modifiedDate DATETIME(6) DEFAULT NULL,
	PRIMARY KEY (surveyId),
	KEY IX_VEC_IS_STATUS_CREATE (status, createDate),
	KEY IX_VEC_IS_USER (userId),
	KEY IX_VEC_IS_DATE (startDate, endDate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS VEC_InternalSurveyOption (
	optionId BIGINT NOT NULL AUTO_INCREMENT,
	surveyId BIGINT NOT NULL,
	optionText VARCHAR(500) NOT NULL,
	sortOrder INT NOT NULL DEFAULT 0,
	createDate DATETIME(6) DEFAULT NULL,
	modifiedDate DATETIME(6) DEFAULT NULL,
	PRIMARY KEY (optionId),
	KEY IX_VEC_ISO_SURVEY_SORT (surveyId, sortOrder)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS VEC_InternalSurveyParticipant (
	participantId BIGINT NOT NULL AUTO_INCREMENT,
	surveyId BIGINT NOT NULL,
	scopeType VARCHAR(20) NOT NULL,
	organizationId BIGINT NOT NULL DEFAULT 0,
	departmentId BIGINT NOT NULL DEFAULT 0,
	userId BIGINT NOT NULL DEFAULT 0,
	createDate DATETIME(6) DEFAULT NULL,
	PRIMARY KEY (participantId),
	KEY IX_VEC_ISP_SURVEY_SCOPE (surveyId, scopeType),
	KEY IX_VEC_ISP_ORG (organizationId),
	KEY IX_VEC_ISP_DEPT (departmentId),
	KEY IX_VEC_ISP_USER (userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS VEC_InternalSurveyVote (
	voteId BIGINT NOT NULL AUTO_INCREMENT,
	surveyId BIGINT NOT NULL,
	optionId BIGINT NOT NULL,
	userId BIGINT NOT NULL,
	userName VARCHAR(255) DEFAULT NULL,
	organizationId BIGINT NOT NULL DEFAULT 0,
	departmentId BIGINT NOT NULL DEFAULT 0,
	createDate DATETIME(6) DEFAULT NULL,
	PRIMARY KEY (voteId),
	UNIQUE KEY UX_VEC_ISV_USER_OPTION (surveyId, userId, optionId),
	KEY IX_VEC_ISV_SURVEY_USER (surveyId, userId),
	KEY IX_VEC_ISV_OPTION (optionId),
	KEY IX_VEC_ISV_ORG (organizationId),
	KEY IX_VEC_ISV_DEPT (departmentId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
