-- =====================================================================
-- Toll Reconciliation Hook — MySQL 8.x / InnoDB / utf8mb4
-- Chạy migration này trên DB master trước khi deploy bundle.
-- DATETIME của dữ liệu nguồn được lưu theo UTC.
-- =====================================================================

CREATE TABLE IF NOT EXISTS vec_hook_nonce (
  id          BIGINT       NOT NULL AUTO_INCREMENT,
  client_id   VARCHAR(100) NOT NULL,
  nonce       VARCHAR(128) NOT NULL,
  received_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at  DATETIME     NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_nonce (client_id, nonce),
  KEY idx_nonce_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vec_hook_request_log (
  id            BIGINT        NOT NULL AUTO_INCREMENT,
  trans_id      VARCHAR(64)   NULL,
  client_id     VARCHAR(100)  NULL,
  source_system VARCHAR(100)  NULL,
  external_id   VARCHAR(255)  NULL,
  record_type   VARCHAR(32)   NULL,
  http_status   INT           NULL,
  auth_ok       TINYINT(1)    NULL,
  result_action VARCHAR(16)   NULL,
  error_code    VARCHAR(64)   NULL,
  error_message VARCHAR(1000) NULL,
  remote_ip     VARCHAR(64)   NULL,
  body_size     INT           NULL,
  raw_body      MEDIUMTEXT    NULL,
  received_at   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_log_client (client_id),
  KEY idx_log_received (received_at),
  KEY idx_log_extid (source_system, external_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vec_recon_traffic (
  id                BIGINT        NOT NULL AUTO_INCREMENT,
  source_system     VARCHAR(100)  NOT NULL,
  external_id       VARCHAR(255)  NOT NULL,
  record_type       VARCHAR(32)   NOT NULL,
  action            VARCHAR(16)   NOT NULL,
  route_code        VARCHAR(64)   NOT NULL,
  route_name        VARCHAR(255)  NOT NULL,
  station_code      VARCHAR(64)   NOT NULL,
  station_name      VARCHAR(255)  NOT NULL,
  occurred_at       DATETIME      NOT NULL COMMENT 'UTC',
  src_created_at    DATETIME      NULL COMMENT 'UTC',
  src_updated_at    DATETIME      NULL COMMENT 'UTC',
  src_created_by    VARCHAR(255)  NULL,
  status            VARCHAR(32)   NOT NULL,
  note              VARCHAR(1000) NULL,
  traffic_date      DATE          NOT NULL,
  vehicle_count     INT           NOT NULL,
  vehicle_type      VARCHAR(64)   NULL,
  lane_code         VARCHAR(64)   NULL,
  shift_code        VARCHAR(64)   NULL,
  from_time         DATETIME      NULL COMMENT 'UTC',
  to_time           DATETIME      NULL COMMENT 'UTC',
  ingested_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ingest_updated_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_trans_id     VARCHAR(64)   NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_src_ext (source_system, external_id),
  KEY idx_traffic_date (traffic_date),
  KEY idx_traffic_route_station (route_code, station_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vec_recon_revenue (
  id                    BIGINT        NOT NULL AUTO_INCREMENT,
  source_system         VARCHAR(100)  NOT NULL,
  external_id           VARCHAR(255)  NOT NULL,
  record_type           VARCHAR(32)   NOT NULL,
  action                VARCHAR(16)   NOT NULL,
  route_code            VARCHAR(64)   NOT NULL,
  route_name            VARCHAR(255)  NOT NULL,
  station_code          VARCHAR(64)   NOT NULL,
  station_name          VARCHAR(255)  NOT NULL,
  occurred_at           DATETIME      NOT NULL COMMENT 'UTC',
  src_created_at        DATETIME      NULL COMMENT 'UTC',
  src_updated_at        DATETIME      NULL COMMENT 'UTC',
  src_created_by        VARCHAR(255)  NULL,
  status                VARCHAR(32)   NOT NULL,
  note                  VARCHAR(1000) NULL,
  revenue_date          DATE          NOT NULL,
  amount                DECIMAL(18,2) NOT NULL,
  currency              VARCHAR(8)    NOT NULL,
  transaction_count     INT           NULL,
  payment_method        VARCHAR(32)   NULL,
  reconciliation_status VARCHAR(64)   NULL,
  ingested_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ingest_updated_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_trans_id         VARCHAR(64)   NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_src_ext (source_system, external_id),
  KEY idx_revenue_date (revenue_date),
  KEY idx_revenue_route_station (route_code, station_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vec_recon_incident (
  id                   BIGINT        NOT NULL AUTO_INCREMENT,
  source_system        VARCHAR(100)  NOT NULL,
  external_id          VARCHAR(255)  NOT NULL,
  record_type          VARCHAR(32)   NOT NULL,
  action               VARCHAR(16)   NOT NULL,
  route_code           VARCHAR(64)   NOT NULL,
  route_name           VARCHAR(255)  NOT NULL,
  station_code         VARCHAR(64)   NOT NULL,
  station_name         VARCHAR(255)  NOT NULL,
  occurred_at          DATETIME      NOT NULL COMMENT 'UTC',
  src_created_at       DATETIME      NULL COMMENT 'UTC',
  src_updated_at       DATETIME      NULL COMMENT 'UTC',
  src_created_by       VARCHAR(255)  NULL,
  status               VARCHAR(32)   NOT NULL,
  note                 VARCHAR(1000) NULL,
  incident_id          VARCHAR(255)  NOT NULL,
  incident_type        VARCHAR(255)  NOT NULL,
  incident_title       VARCHAR(255)  NULL,
  incident_description TEXT          NULL,
  resolved_at          DATETIME      NULL COMMENT 'UTC',
  resolution_note      TEXT          NULL,
  ingested_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ingest_updated_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_trans_id        VARCHAR(64)   NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_src_ext (source_system, external_id),
  KEY idx_incident_status (status),
  KEY idx_incident_occurred (occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vec_recon_event (
  id                BIGINT        NOT NULL AUTO_INCREMENT,
  source_system     VARCHAR(100)  NOT NULL,
  external_id       VARCHAR(255)  NOT NULL,
  record_type       VARCHAR(32)   NOT NULL,
  action            VARCHAR(16)   NOT NULL,
  route_code        VARCHAR(64)   NOT NULL,
  route_name        VARCHAR(255)  NOT NULL,
  station_code      VARCHAR(64)   NOT NULL,
  station_name      VARCHAR(255)  NOT NULL,
  occurred_at       DATETIME      NOT NULL COMMENT 'UTC',
  src_created_at    DATETIME      NULL COMMENT 'UTC',
  src_updated_at    DATETIME      NULL COMMENT 'UTC',
  src_created_by    VARCHAR(255)  NULL,
  status            VARCHAR(32)   NOT NULL,
  note              VARCHAR(1000) NULL,
  event_id          VARCHAR(255)  NOT NULL,
  event_name        VARCHAR(255)  NOT NULL,
  event_type        VARCHAR(255)  NOT NULL,
  event_content     TEXT          NULL,
  ingested_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ingest_updated_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_trans_id     VARCHAR(64)   NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_src_ext (source_system, external_id),
  KEY idx_event_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vec_recon_error (
  id                BIGINT        NOT NULL AUTO_INCREMENT,
  source_system     VARCHAR(100)  NOT NULL,
  external_id       VARCHAR(255)  NOT NULL,
  record_type       VARCHAR(32)   NOT NULL,
  action            VARCHAR(16)   NOT NULL,
  route_code        VARCHAR(64)   NOT NULL,
  route_name        VARCHAR(255)  NOT NULL,
  station_code      VARCHAR(64)   NOT NULL,
  station_name      VARCHAR(255)  NOT NULL,
  occurred_at       DATETIME      NOT NULL COMMENT 'UTC',
  src_created_at    DATETIME      NULL COMMENT 'UTC',
  src_updated_at    DATETIME      NULL COMMENT 'UTC',
  src_created_by    VARCHAR(255)  NULL,
  status            VARCHAR(32)   NOT NULL,
  note              VARCHAR(1000) NULL,
  error_id          VARCHAR(255)  NOT NULL,
  request_name      VARCHAR(255)  NOT NULL,
  error_type        VARCHAR(255)  NOT NULL,
  error_description TEXT          NULL,
  priority          VARCHAR(16)   NULL,
  ingested_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ingest_updated_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_trans_id     VARCHAR(64)   NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_src_ext (source_system, external_id),
  KEY idx_error_status (status),
  KEY idx_error_priority (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
