CREATE TABLE IF NOT EXISTS VEC_WorkflowReviewHistory (
  historyId BIGINT NOT NULL AUTO_INCREMENT,
  companyId BIGINT NOT NULL DEFAULT 0,
  workflowTaskId BIGINT NOT NULL,
  workflowInstanceId BIGINT NULL DEFAULT 0,
  assetType VARCHAR(255) NULL,
  assetPrimaryKey BIGINT NULL DEFAULT 0,
  assetTitle VARCHAR(500) NULL,
  assetContent LONGTEXT NULL,
  parentClassName VARCHAR(255) NULL,
  parentClassPK BIGINT NULL DEFAULT 0,
  creatorUserId BIGINT NULL DEFAULT 0,
  creatorUserName VARCHAR(255) NULL,
  assigneeUserId BIGINT NULL DEFAULT 0,
  assigneeUserName VARCHAR(255) NULL,
  completedByUserId BIGINT NULL DEFAULT 0,
  completedByUserName VARCHAR(255) NULL,
  reviewComment LONGTEXT NULL,
  status VARCHAR(50) NULL,
  taskName VARCHAR(255) NULL,
  createDate DATETIME(6) NULL,
  modifiedDate DATETIME(6) NULL,
  dueDate DATETIME(6) NULL,
  completedDate DATETIME(6) NULL,
  PRIMARY KEY (historyId),
  UNIQUE KEY IX_VEC_WorkflowReviewHistory_Task (workflowTaskId),
  KEY IX_VEC_WorkflowReviewHistory_Company_Status
    (companyId, status, createDate),
  KEY IX_VEC_WorkflowReviewHistory_Asset (assetType, assetPrimaryKey),
  KEY IX_VEC_WorkflowReviewHistory_Assignee (companyId, assigneeUserId),
  KEY IX_VEC_WorkflowReviewHistory_CompletedBy (companyId, completedByUserId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
