export const CALENDAR_GROUPS = [
  { key: "ban-lanh-dao", label: "Ban lãnh đạo" },
  { key: "dang-uy-vec", label: "Đảng ủy VEC" },
  { key: "ban-kiem-soat", label: "Ban Kiểm soát" },
  { key: "tong-hop-cac-phong", label: "Tổng hợp các phòng" },
  { key: "trung-tam-cntt", label: "Trung tâm CNTT" },
  { key: "tt-gsktvh", label: "TT GSKTVH đường cao tốc Việt Nam" },
  { key: "tt-vhkt-danang", label: "TT VHKT Đà Nẵng - Quảng Ngãi" },
  { key: "ban-qlda-bac", label: "Ban QLDA các đường cao tốc phía Bắc" },
  { key: "ban-qlda-nam", label: "Ban QLDA các đường cao tốc phía Nam" },
  { key: "ban-qlda-danang", label: "Ban QLDA Đà Nẵng - Quảng Ngãi" },
];

export const EVENT_FILTER_OPTIONS = [
  { value: "all", label: "Tất cả lãnh đạo" },
];

export const PARTICIPANT_FILTER_OPTIONS = [
  { value: "all", label: "Tất cả người tham gia" },
];

export const MONTHS = [
  { value: 1, label: "Tháng 1" },
  { value: 2, label: "Tháng 2" },
  { value: 3, label: "Tháng 3" },
  { value: 4, label: "Tháng 4" },
  { value: 5, label: "Tháng 5" },
  { value: 6, label: "Tháng 6" },
  { value: 7, label: "Tháng 7" },
  { value: 8, label: "Tháng 8" },
  { value: 9, label: "Tháng 9" },
  { value: 10, label: "Tháng 10" },
  { value: 11, label: "Tháng 11" },
  { value: 12, label: "Tháng 12" },
];

export const YEARS = [
  { value: 2024, label: "2024" },
  { value: 2025, label: "2025" },
  { value: 2026, label: "2026" },
  { value: 2027, label: "2027" },
];

export const mockEventsData = [
  {
    key: 1,
    ngayThang: "Sáng",
    noiDungCongViec: "Chủ tịch HĐTV - Trương Việt Dũng",
    time: "08:00 AM",
    detail: "Dự Hội nghị Người lao động VEC",
    chuanBi: "-",
    thanhPhanThamGia: "CT HĐTV và TGĐ",
    diaDiem: "Hội trường T5",
    chuTri: "TGĐ, CT CĐ",
  },
  {
    key: 2,
    ngayThang: "",
    noiDungCongViec: "PTGĐ - Đảng Hoài Nam",
    time: "08:00 AM",
    detail: "Làm việc với Vụ KHTC và Cục KT QLXD Bộ XD",
    chuanBi: "Ban TCKT, Ban TD",
    thanhPhanThamGia: "Ban TCKT, TD, Ban DNGN",
    diaDiem: "Bộ XD",
    chuTri: "-",
  },
  {
    key: 3,
    ngayThang: "Hôm nay\n06/01",
    noiDungCongViec: "Chủ tịch HĐTV - Trương Việt Dũng",
    time: "01:00 PM",
    detail: "Họp BTV ĐUVEC",
    chuanBi: "TCNS, VP Đảng Đoàn",
    thanhPhanThamGia: "Kinh mời các d/c UV BTV",
    diaDiem: "Phòng họp trục tuyến tầng 2 - Trụ sở VEC",
    chuTri: "Đ/c Trương Việt Dũng\nBí thư Đảng ủy VEC",
  },
  {
    key: 4,
    ngayThang: "Chiều",
    noiDungCongViec: "TGĐ - Phạm Hồng Quang",
    time: "01:00 PM",
    detail: "Họp BTV ĐUVEC",
    chuanBi: "TCNS, VP Đảng Đoàn",
    thanhPhanThamGia: "Kinh mời các d/c UV BTV",
    diaDiem: "Phòng họp trục tuyến tầng 2 - Trụ sở VEC",
    chuTri: "Đ/c Trương Việt Dũng\nBí thư Đảng ủy VEC",
  },
  {
    key: 5,
    ngayThang: "",
    noiDungCongViec: "TGĐ - Phạm Hồng Quang",
    time: "02:00 AM",
    detail: "Dự Hội nghị tổng kết công tác 2025, nhiệm vụ 2026 VEC",
    chuanBi: "-",
    thanhPhanThamGia: "Theo GM",
    diaDiem: "Hội trường T5",
    chuTri: "CT HĐTV, TGĐ",
  },
  {
    key: 6,
    ngayThang: "",
    noiDungCongViec: "Chủ tịch HĐTV - Trương Việt Dũng",
    time: "08:00 AM",
    detail: "Dự Hội nghị Người lao động VEC",
    chuanBi: "-",
    thanhPhanThamGia: "CT HĐTV và TGĐ",
    diaDiem: "Phòng làm việc của CT HĐTV",
    chuTri: "Chủ tịch HĐTV",
  },
  {
    key: 7,
    ngayThang: "Sáng",
    noiDungCongViec: "PTGĐ - Đảng Hoài Nam",
    time: "08:00 AM",
    detail: "Làm việc với Vụ KHTC và Cục KT QLXD Bộ XD",
    chuanBi: "Ban TCKT",
    thanhPhanThamGia: "Ban TCKT, TD, Đt, PC, Tổ 20E4, tư vấn",
    diaDiem: "Bộ XD",
    chuTri: "-",
  },
  {
    key: 8,
    ngayThang: "Thứ 2\n05/01",
    noiDungCongViec: "PTGĐ - Kiều Hưng",
    time: "08:00 AM",
    detail: "Dự hội nghị BCH Đảng bộ VEC",
    chuanBi: "Ban TCKT",
    thanhPhanThamGia: "Ban TCKT, TD, Đt, PC, Tổ 20E4, tư vấn",
    diaDiem: "Phòng họp trục tuyến tầng 2",
    chuTri: "PTGĐ Kiều Hưng",
  },
  {
    key: 9,
    ngayThang: "",
    noiDungCongViec: "Chủ tịch HĐTV - Trương Việt Dũng",
    time: "01:00 PM",
    detail: "Họp BTV ĐUVEC",
    chuanBi: "TCNS, VP Đảng Đoàn",
    thanhPhanThamGia: "Kinh mời các d/c UV BTV",
    diaDiem: "Phòng họp trục tuyến tầng 2 - Trụ sở VEC",
    chuTri: "Đ/c Trương Việt Dũng\nBí thư Đảng ủy VEC",
  },
  {
    key: 10,
    ngayThang: "Chiều",
    noiDungCongViec: "TGĐ - Phạm Hồng Quang",
    time: "01:00 PM",
    detail: "Họp BTV ĐUVEC",
    chuanBi: "TCNS, VP Đảng Đoàn",
    thanhPhanThamGia: "Kinh mời các d/c UV BTV",
    diaDiem: "Phòng họp trục tuyến tầng 2 - Trụ sở VEC",
    chuTri: "Đ/c Trương Việt Dũng\nBí thư Đảng ủy VEC",
  },
  {
    key: 11,
    ngayThang: "",
    noiDungCongViec: "TGĐ - Phạm Hồng Quang",
    time: "02:00 AM",
    detail: "Dự Hội nghị tổng kết công tác 2025, nhiệm vụ 2026 VEC",
    chuanBi: "-",
    thanhPhanThamGia: "Theo GM",
    diaDiem: "Hội trường T5",
    chuTri: "CT HĐTV, TGĐ",
  },
];
